#! /bin/bash

# This script runs Space Ranger in a spaceranger:latest Docker container in hawai.
# To do so, Conda must be initialized for shell interactions previously and a user account with permissions must be used.

################
# Requirements #
################

# Docker image: spaceranger:latest
# Conda environment: spaceranger_env

###########
# Options #
###########

# default values
DRY_RUN=0
SPACE_RANGER_NAMES=0

while getopts "a:c:df:g:i:j:l:m:n:o:pr:s:v:" param
do
	case $param in		
		# Visium area identifier
		a) AREA=$OPTARG;;
		# Max cores Space Ranger may request
		c) LOCAL_CORES=$OPTARG;;
		# Dry run
		d) DRY_RUN=1;;
		# Path to genome index directory generated by spaceranger mkref
		g) GENOME_INDEX_DIR=$OPTARG;;
		# Path to H&E brightfield image in either TIFF or JPG format
		i) IMAGE=$OPTARG;;
		# Name of Space Ranger output directory (spaceranger count --id option)
		j) ID=$OPTARG;;
		# path to report file
		l) REPORT_FILE=$OPTARG;;
		# Max RAM Space Ranger may request
		m) LOCAL_MEMORY=$OPTARG;;
		# Dataset name
		n) EXP_NAME=$OPTARG;;
		# Path to output directory
		o) OUTPUT_DIR=$OPTARG;; # must be /home/christophe.lepriol/spatial_transcriptomics_nfs...
		# Fit input Fastq file basenames with the naming conventions of bcl2fastq and mkfastq used by Space Ranger
		p) SPACE_RANGER_NAMES=1;;
		# Path to R1 reads ungzipped fastq file
		r) R1_FASTQ_FILE=$OPTARG;;
		# Path to R2 reads ungzipped fastq file
		s) R2_FASTQ_FILE=$OPTARG;;
		# Visium slide serial number
		v) VISIUM_SLIDE=$OPTARG;;
		:) echo "Option -$OPTARG expects an argument. Exit." ; exit;;
		\?) echo "Unvalid option -$OPTARG. Exit." ; exit;;
	esac
done

#############
# Functions #
#############

function check_cmd_exit_code {
	local cmd=$@
	
	echo "${cmd}"
	eval ${cmd}
	local exit_code=$?
	if [ ${exit_code} -ne 0 ]; then
		local message=${cmd%% *}
		echo "Error while ${message} execution, exit code: ${exit_code}"
		exit ${exit_code}
	fi
}

function create_directory {
	local DIR_TO_CREATE=$1
	local DRY_RUN=$2
	
	if [ ! -d ${DIR_TO_CREATE} ]; then
		echo "create directory: ${DIR_TO_CREATE}"
		if [ ${DRY_RUN} -eq 0 ]; then
			mkdir -p ${DIR_TO_CREATE}
		fi
	else
		echo "${DIR_TO_CREATE} already exists."
	fi
}

function run_cmd {
	local cmd=$@
	
	echo "${cmd}"
	eval time ${cmd}
	local error_code=$?
	if [ ${error_code} -ne 0 ]; then
		local message=${cmd%% *}
		echo "Error while ${message} execution."
		exit ${error_code}
	fi
}


##########
# Script #
##########
# source ~/.bashrc otherwise conda: command not found
CMD="source ~/.bashrc"
run_cmd ${CMD}

# Verify Conda is intalled and get base environment path
CONDA_BASE=$(conda info --base)
if [ $? -eq 0 ]; then
	# add Conda to path 
	source ${CONDA_BASE}/etc/profile.d/conda.sh
	
	# activate 'spaceranger_env' Conda environment
	CMD="conda activate spaceranger_env"
	check_cmd_exit_code ${CMD}
	
	# add Space Ranger to PATH
	CMD="export PATH=/opt/spaceranger-1.2.2:$PATH"
	check_cmd_exit_code ${CMD}
	
	# move to output directory
	create_directory ${OUTPUT_DIR} ${DRY_RUN}
	CMD="cd ${OUTPUT_DIR}"
	run_cmd ${CMD}
	
	# options
	if [ ! -z ${LOCAL_CORES} ]; then
		LOCAL_CORES_OPTION=" --localcores=${LOCAL_CORES}"
	else
		LOCAL_CORES_OPTION=""
	fi
	
	if [ ! -z ${LOCAL_MEMORY} ]; then
		LOCAL_MEMORY_OPTION=" --localmem=${LOCAL_MEMORY}"
	else
		LOCAL_MEMORY_OPTION=""
	fi

	# create tmp output directory if needed
	TMP_DIR=${OUTPUT_DIR}/tmp
	create_directory ${TMP_DIR} ${DRY_RUN}
	
	# initiate report file
	echo -e "# Space Ranger\n" >> ${REPORT_FILE}
	echo -e "## Inputs\nR1 fastq file: ${R1_FASTQ_FILE}\nR2 fastq file: ${R2_FASTQ_FILE}\n" >> ${REPORT_FILE}
	
	if [ ${SPACE_RANGER_NAMES} -eq 1 ]; then
		# rename fastq files to fit with 10x genomics naming conventions: https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/fastq-input
		## R1 fastq file
		if (expr match "${R1_FASTQ_FILE}" '.*\(.gz$\)'); then
			NEW_R1_FASTQ_FILE=${TMP_DIR}/${EXP_NAME}_L001_R1_001.fastq.gz
		else
			if (expr match "${R1_FASTQ_FILE}" '.*\(.fastq$\)'); then
				NEW_R1_FASTQ_FILE=${TMP_DIR}/${EXP_NAME}_L001_R1_001.fastq
			else
				echo "The extension of ${R1_FASTQ_FILE} is neither '.fastq' nor '.fastq.gz'. Exit."
				exit 1
			fi
		fi
		CMD="cp -p ${R1_FASTQ_FILE} ${NEW_R1_FASTQ_FILE}"
		run_cmd ${CMD}
		
		## R2 fastq file
		if (expr match "${R2_FASTQ_FILE}" '.*\(.gz$\)'); then
			NEW_R2_FASTQ_FILE=${TMP_DIR}/${EXP_NAME}_L001_R2_001.fastq.gz
		else
			if (expr match "${R2_FASTQ_FILE}" '.*\(.fastq$\)'); then
				NEW_R2_FASTQ_FILE=${TMP_DIR}/${EXP_NAME}_L001_R2_001.fastq
			else
				echo "The extension of ${R2_FASTQ_FILE} is neither '.fastq' nor '.fastq.gz'. Exit."
				exit 1
			fi
		fi
		CMD="cp -p ${R2_FASTQ_FILE} ${NEW_R2_FASTQ_FILE}"
		run_cmd ${CMD}
		
		FASTQS_DIR=${TMP_DIR}
	else
		if [ ${SPACE_RANGER_NAMES} -eq 0 ]; then
			R1_FASTQ_FILE_DIR=$(dirname ${R1_FASTQ_FILE})
			R2_FASTQ_FILE_DIR=$(dirname ${R2_FASTQ_FILE})
			if [ ${R1_FASTQ_FILE_DIR} = ${R2_FASTQ_FILE_DIR} ]; then
				FASTQS_DIR=${R1_FASTQ_FILE_DIR}
			else
				echo "The Fastq files ${R1_FASTQ_FILE} and ${R2_FASTQ_FILE} are not stored in the same directory. They must be stored in the same directory to run Space Ranger. Exit."
				exit 1
			fi
			
		fi
	fi
	
	# get sample ID
	SAMPLE=$(echo ${EXP_NAME} | cut -d "_" -f 1,2)
	
	# Space Ranger count
	CMD="spaceranger count --id=${ID} --sample=${SAMPLE} --fastqs=${FASTQS_DIR}/ --transcriptome=${GENOME_INDEX_DIR} --image=${IMAGE} --slide=${VISIUM_SLIDE} --area=${AREA}${LOCAL_CORES_OPTION}${LOCAL_MEMORY_OPTION}"
	echo -e "## spaceranger count command line:\n${CMD}" >> ${REPORT_FILE}
	if [ ${DRY_RUN} -eq 1 ]; then
		echo ${CMD}
	else
		run_cmd ${CMD}
	fi
	
	# cleaning
	if [ ${SPACE_RANGER_NAMES} -eq 1 ]; then
		## remove renamed fastq files
		CMD="rm -f ${NEW_R1_FASTQ_FILE}"
		if [ ${DRY_RUN} -eq 1 ]; then
			echo ${CMD}
		else
			run_cmd ${CMD}
		fi
		CMD="rm -f ${NEW_R2_FASTQ_FILE}"
		if [ ${DRY_RUN} -eq 1 ]; then
			echo ${CMD}
		else
			run_cmd ${CMD}
		fi
	fi
	## remove tmp BAM files
	WRITE_POS_BAM_FORK_DIR=${OUTPUT_DIR}/${ID}/SPATIAL_RNA_COUNTER_CS/SPATIAL_RNA_COUNTER/_BASIC_SPATIAL_RNA_COUNTER/WRITE_POS_BAM/fork0
	WRITE_POS_BAM_FILES_DIR=${WRITE_POS_BAM_FORK_DIR}/files
	if [ -d ${WRITE_POS_BAM_FILES_DIR} ]; then
		CMD="rm -f ${WRITE_POS_BAM_FILES_DIR}/*.bam"
		if [ ${DRY_RUN} -eq 1 ]; then
			echo ${CMD}
		else
			run_cmd ${CMD}
		fi
	fi
	WRITE_POS_BAM_JOIN_DIR=${WRITE_POS_BAM_FORK_DIR}/join/files
	if [ -d ${WRITE_POS_BAM_JOIN_DIR} ]; then
		CMD="rm -f ${WRITE_POS_BAM_FORK_DIR}/join*/files/*.bam"
		if [ ${DRY_RUN} -eq 1 ]; then
			echo ${CMD}
		else
			run_cmd ${CMD}
		fi
	fi

	# deactivate 'spaceranger_env' Conda environment
	CMD="conda deactivate"
	check_cmd_exit_code ${CMD}
else
	echo "The 'conda info --base' command exit code is not 0, Conda does seem to installed. Exit."
	exit 1
fi

